webapp/config/routes.rb
Chatter::Application.routes.draw do
  
  resources :channels 
  resources :messages
  resources :users
  
  match "/auth/:provider/callback" => "sessions#create"
  match "/register_client" => "users#register_client"
  match "/login" => "sessions#create"
  match "/signout" => "sessions#destroy"
  match "/local_login_form" => "sessions#new"
  match "/local_login" => "sessions#local_login"
  match "/update_chat" => "messages#update_chat"
  match "/message_client" => "messages#create_client"
  match '/chat' => "messages#chat"
  match "/register_channel" => "users#register_channel"
  root to: 'messages#index'
end

webapp/app/models/channel.rb
class Channel < ActiveRecord::Base
 
 validates :name, :presence => {:message => I18n.t(:name_channel_error)}
 validates :name, :uniqueness => {:message => I18n.t(:name_unique_channel_error)}

end

webapp/app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  
  
  before_filter :current_user? , :except => [:index]

  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @channels }
      format.xml {render xml: @channels}
    end
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @channel = Channel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @channel }
    end
  end

  # GET /channels/new
  # GET /channels/new.json
  def new
    @channel = Channel.new
    respond_to do |format|
      format.json { render json: @channel }
      format.html
    end
  end

  # GET /channels/1/edit
  def edit
    @channel = Channel.find(params[:id])
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(params[:channel])
    respond_to do |format|
      if @channel.save
        format.js {@user_msg = "#{t(:new_channel_created)} : #{@channel.name}"}
        format.json { render json: @channel, status: :created, location: @channel }
        format.html{
           PrivatePub.publish_to('/messages',
           "$('select#channel_id').append('<option value = #{@channel.id} > #{@channel.name}</option>');
           $('#msg-channel').css('display','block');$('#msg-channel').html('se ha creado un nuevo canal');
           $('#msg-channel').fadeOut(2000);$('#channel_id').trigger('liszt:updated');")
           redirect_to channels_path
        }
      else
        @error_msg = @channel.errors.full_messages[0]
        format.js { render action: "errors" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
        format.html {render action: "new"}
      end
    end
  end

  # PUT /channels/1
  # PUT /channels/1.json
  def update
    @channel = Channel.find(params[:id])
    respond_to do |format|
      if @channel.update_attributes(params[:channel])
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel = Channel.find(params[:id])
    @channel.destroy
    respond_to do |format|
      format.html { 
        PrivatePub.publish_to('/messages', "$(\"#channel_id option:regex(value,#{@channel.id})\").remove();
        $('#msg-channel').css('display','block');$('#msg-channel').html('se ha eliminado un nuevo canal');
        $('#channel_id').trigger('liszt:updated');$('#msg-channel').fadeOut(2000);")
        redirect_to channels_url
      }
      format.json { head :ok }
    end
  end
  
end

webapp/app/helpers/channels_helper.rb
module ChannelsHelper
end

webapp/app/views/channels/_form.html.erb
<div class= "form">
<%= form_for @channel, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label t(:name), :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                channels_path, :class => 'btn' %>
  </div>
<% end %>
</div>

webapp/app/views/channels/create.js.erb
$('form#new_channel')[0].reset();
<% publish_to '/messages' do %>
	$('#msg-channel').css('display','block');
	$('#msg-channel').html("<%= j @user_msg %>");
	$('#msg-channel').fadeOut(2000);
	$('select#channel_id').append("<option value = <%= @channel.id %> > <%= j @channel.name %></option>");
<% end %>

webapp/app/views/channels/edit.html.erb
<%- model_class = @channel.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Editar canales") %></h1>
<%= render :partial => 'form' %>

webapp/app/views/channels/errors.js.erb
$('#msg-channel').css('display','block');
$("#msg-channel").html("<%= @error_msg %>");
$('#msg-channel').fadeOut(2000);

webapp/app/views/channels/index.html.erb
<%- model_class = Channel.new.class -%>
<h1><%=t '.title', :default => t(:channels) %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t(:id) %></th>
      <th><%= t(:name) %></th>
      <th><%= t(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @channels.each do |channel| %>
      <tr>
        <td><%= link_to channel.id, channel_path(channel) %></td>
        <td><%= channel.name %></td>
        <td><%=l channel.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_channel_path(channel), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      channel_path(channel),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_channel_path,
            :class => 'btn btn-primary' %>

webapp/app/views/channels/new.html.erb
<%- model_class = @channel.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

webapp/app/views/channels/show.html.erb
<%- model_class = @channel.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @channel.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              channels_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_channel_path(@channel), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              channel_path(@channel),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>