webapp/config/routes.rb
Chatter::Application.routes.draw do
  
  resources :channels 
  resources :messages
  resources :users
  
  match "/auth/:provider/callback" => "sessions#create"
  match "/register_client" => "users#register_client"
  match "/login" => "sessions#create"
  match "/signout" => "sessions#destroy"
  match "/local_login_form" => "sessions#new"
  match "/local_login" => "sessions#local_login"
  match "/update_chat" => "messages#update_chat"
  match "/message_client" => "messages#create_client"
  match '/chat' => "messages#chat"
  match "/register_channel" => "users#register_channel"
  root to: 'messages#index'
end

webapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatter</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
	<!--[if lt IE 9]>
	    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
	  <![endif]-->
  </head>
  <body>
	<div class="navbar navbar-fixed-top">
	    <div class="navbar-inner">
	      <div class="container">
	        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	        </a>
	        <a class="brand" href= <%= root_url %> >Chatter...</a>
	        <div class="nav-collapse">
	          <ul class="nav">
				<% if current_user %>
				  <li><a class="brand"><%= "Welcome #{current_user.username}" %></a></li>				 
				  <% if can? :manage, Channel %>
				   	<li><%= link_to t(:register), new_user_path %></li>
				  	<li><%= link_to t(:channels), channels_path %></li>
				  	<li><%= link_to t(:users), users_path %></li>
				  <% end %>
				  <li><%= link_to t(:sign_out), signout_path %></li>
				<% else %>
				  <li><%= link_to t(:sign_in_twitter), "/auth/twitter" %></li>
				  <li><%= link_to t(:sign_in_facebook), "/auth/facebook" %></li>
				  <li><%= link_to t(:sign_in_local), "/local_login_form" %></li>
				<% end %>
	          </ul>
	        </div>
	      </div>
	    </div>
	  </div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
	  <div class = "container">
		<div class= "row">
      	<div class= "span12"><%= yield %></div>
		</div>
	  </div>
  </body>
</html>